# Generated by Django 4.2.6 on 2023-10-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=30, unique=True, verbose_name="아이디"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="비밀번호")),
                ("nickname", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True,
                        default="media/userProfile/default.png",
                        null=True,
                        upload_to="media/userProfile",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="계정 활성화 여부"),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자 여부")),
                ("updated_at", models.DateField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
