# Generated by Django 4.2.6 on 2023-10-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="수정일"),
        ),
    ]
